### ISSUE TITLE
connect ETIMEDOUT 151.101.122.214:443

### ISSUE THREAD

**Issue by Arubinu** [skarab42/marv#200]
**Describe the bug**
Erreur survenue sans utilisation de Marv, après le message affiché Marv indique "Déconnecté, En attente de connexion..." et demande un redémarrage pour fonctionner.

**To Reproduce**
1. Laisser Marv tourner en fond

**Expected behavior**
Qu'il se reconnecte malgré l'erreur.

**Desktop**
- OS: Windows_NT 10.0.19042 win32
 - Browser: Marv
 - Version: https://github.com/skarab42/marv/tree/3808fdacbf8734b41ac2f6da233994a3112e5130

**Stack trace**
```
UnhandledRejection: FetchError: request to https://api.twitch.tv/helix/users?login=Arubinu42 failed, reason: connect ETIMEDOUT 151.101.122.214:443
    at ClientRequest.<anonymous> (C:\Users\pyrof\Documents\Dev\marv\app\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Arubinu** [comment]
Je n'ai pas grand chose en vrai: `server-2021-03-03.log`
```
[21-03-03 00:03:98][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 00:03:99][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 00:03:46][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 00:03:46][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 00:03:06][server][error] UnhandledRejection: FetchError: request to https://api.twitch.tv/helix/users?login=Arubinu42 failed, reason: connect ETIMEDOUT 151.101.122.214:443
    at ClientRequest.<anonymous> (C:\Users\pyrof\Documents\Dev\marv\app\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) 
[21-03-03 00:03:79][server][info] Starting... 
[21-03-03 00:03:96][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 00:03:54][server][info] Client connected 
[21-03-03 00:03:13][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 00:03:14][server][info] Chat connected 
[21-03-03 00:03:61][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 00:03:61][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 00:03:61][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 01:03:59][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 01:03:59][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 01:03:31][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 01:03:32][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 01:03:72][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 01:03:72][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 01:03:02][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 01:03:02][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 02:03:84][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 02:03:84][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 02:03:39][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 02:03:39][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 03:03:62][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 03:03:62][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 04:03:30][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 04:03:30][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 04:03:09][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 04:03:09][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 05:03:25][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 05:03:25][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 05:03:49][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 05:03:49][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 05:03:21][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 05:03:21][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 06:03:11][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 06:03:11][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 06:03:68][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 06:03:68][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 06:03:14][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"streamlabs"}}
[21-03-03 06:03:80][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 06:03:81][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 06:03:81][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 07:03:25][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 07:03:25][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 07:03:61][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 07:03:61][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 07:03:77][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 07:03:77][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 07:03:80][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 07:03:81][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 07:03:06][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 07:03:06][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 08:03:56][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 08:03:56][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 08:03:17][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 08:03:17][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 08:03:43][server][info] Client connected 
[21-03-03 08:03:45][server][info] Client connected 
[21-03-03 08:03:47][server][info] Overlay connected 
[21-03-03 08:03:31][server][info] Starting... 
[21-03-03 08:03:34][server][info] Client connected 
[21-03-03 08:03:58][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 08:03:06][server][info] Client connected 
[21-03-03 08:03:23][server][info] Client connected 
[21-03-03 08:03:23][server][info] Overlay connected 
[21-03-03 08:03:14][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 08:03:14][server][info] Chat connected 
[21-03-03 08:03:78][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 08:03:78][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 08:03:78][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 08:03:05][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"toxicrebirth","message":"!test","isBroadcaster":false,"isMod":false,"isVip":false,"isSubscriber":false}}
[21-03-03 08:03:06][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!test","command":{"prefix":"!","name":"test","args":[]},"isBroadcaster":false,"isMod":false,"isVip":false,"isSubscriber":false,"user":"toxicrebirth"}}
[21-03-03 08:03:100][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"toxicrebirth"}}
[21-03-03 08:03:92][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"toxicrebirth","message":"!test","isBroadcaster":false,"isMod":false,"isVip":false,"isSubscriber":false}}
[21-03-03 08:03:92][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!test","command":{"prefix":"!","name":"test","args":[]},"isBroadcaster":false,"isMod":false,"isVip":false,"isSubscriber":false,"user":"toxicrebirth"}}
[21-03-03 08:03:90][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 1","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:90][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 1","command":{"prefix":"!","name":"pause","args":["1"]},"minutes":1,"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 08:03:22][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 2","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:65][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 2","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:66][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 2","command":{"prefix":"!","name":"pause","args":["2"]},"minutes":2,"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 08:03:23][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!jeu","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:24][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!jeu","command":{"prefix":"!","name":"jeu","args":[]},"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 08:03:71][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 2","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:71][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 2","command":{"prefix":"!","name":"pause","args":["2"]},"minutes":2,"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 08:03:68][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!camera","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:68][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!camera","command":{"prefix":"!","name":"camera","args":[]},"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 08:03:49][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 5","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:78][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 5","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 08:03:78][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 5","command":{"prefix":"!","name":"pause","args":["5"]},"minutes":5,"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 08:03:06][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"streamlabs","message":"Tu veux voir ma liste de jeu (et me conseiller) ? Clique ici: https://shorturl.at/dmozF","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 08:03:90][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"streamlabs","message":"Profitez du lien d'affiliation de la chaîne pour Instant Gaming: https://www.instant-gaming.com?igr=arubinu","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 08:03:27][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"`index.html`","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:67][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 09:03:67][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 09:03:78][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 09:03:78][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 09:03:85][server][info] Starting... 
[21-03-03 09:03:03][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 09:03:11][server][info] Client connected 
[21-03-03 09:03:63][server][info] Client connected 
[21-03-03 09:03:60][server][info] Client connected 
[21-03-03 09:03:60][server][info] Overlay connected 
[21-03-03 09:03:14][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 09:03:15][server][info] Chat connected 
[21-03-03 09:03:89][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"rghettehjes","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:58][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"test","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:16][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 09:03:16][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 09:03:16][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"toxicrebirth"}}
[21-03-03 09:03:16][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 09:03:78][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"toxicrebirth"}}
[21-03-03 09:03:90][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:74][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:29][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:60][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:75][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:18][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:59][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 09:03:53][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 10:03:12][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 10:03:14][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 10:03:86][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 10:03:06][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 10:03:27][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:27][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:32][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:32][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:84][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est pas bien dans sa peau mais il en a rien à foutre et vie tout de même ca vie dénuée de sens ...!","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 10:03:89][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:90][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:44][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:44][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:50][server][info] Client connected 
[21-03-03 10:03:76][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:76][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:44][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:44][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:04][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 10:03:05][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:41][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"havethis2"}}
[21-03-03 10:03:41][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 11:03:35][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"havethis2"}}
[21-03-03 11:03:69][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 11:03:92][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 12:03:49][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 12:03:37][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 12:03:24][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 12:03:67][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 12:03:51][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 12:03:48][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 13:03:25][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"lol_davy"}}
[21-03-03 13:03:58][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"lol_davy"}}
[21-03-03 13:03:36][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 13:03:76][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 14:03:82][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 14:03:23][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 14:03:97][server][info] Starting... 
[21-03-03 14:03:90][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 14:03:56][server][info] Client connected 
[21-03-03 14:03:43][server][info] Client connected 
[21-03-03 14:03:16][server][info] Client connected 
[21-03-03 14:03:16][server][info] Overlay connected 
[21-03-03 14:03:26][server][info] Client connected 
[21-03-03 14:03:20][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 14:03:20][server][info] Chat connected 
[21-03-03 14:03:74][server][info] Starting... 
[21-03-03 14:03:88][server][info] Client connected 
[21-03-03 14:03:93][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 14:03:46][server][info] Client connected 
[21-03-03 14:03:07][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 14:03:08][server][info] Chat connected 
[21-03-03 14:03:51][server][info] Client connected 
[21-03-03 14:03:54][server][info] Client connected 
[21-03-03 14:03:54][server][info] Overlay connected 
[21-03-03 14:03:100][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 14:03:00][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 14:03:93][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 14:03:54][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 15:03:66][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 15:03:15][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 15:03:89][server][info] Client disconnected 
[21-03-03 16:03:64][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 16:03:20][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"violets_tv"}}
[21-03-03 16:03:98][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"violets_tv"}}
[21-03-03 18:03:65][server][info] Starting... 
[21-03-03 18:03:79][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 18:03:31][server][info] Client connected 
[21-03-03 18:03:32][server][info] Overlay connected 
[21-03-03 18:03:48][server][info] Client connected 
[21-03-03 18:03:96][server][info] Client connected 
[21-03-03 18:03:01][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 18:03:01][server][info] Chat connected 
[21-03-03 18:03:36][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 18:03:62][server][info] Starting... 
[21-03-03 18:03:77][server][info] Client connected 
[21-03-03 18:03:79][server][info] Overlay connected 
[21-03-03 18:03:81][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 18:03:78][server][info] Client connected 
[21-03-03 18:03:35][server][info] Client connected 
[21-03-03 18:03:95][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 18:03:95][server][info] Chat connected 
[21-03-03 18:03:03][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 19:03:80][server][info] Starting... 
[21-03-03 19:03:98][server][info] Marv v1.6.0 | Running on http://localhost:4244 
[21-03-03 19:03:00][server][info] Client connected 
[21-03-03 19:03:01][server][info] Overlay connected 
[21-03-03 19:03:55][server][info] Client connected 
[21-03-03 19:03:49][server][info] Client connected 
[21-03-03 19:03:20][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"arubinu42"}}
[21-03-03 19:03:20][server][info] Chat connected 
[21-03-03 19:03:56][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"streamlabs"}}
[21-03-03 20:03:45][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"arubinu42","message":"est une merde !","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 20:03:70][server][debug] pushActions {"eventName":"onAction","eventProps":{"user":"leveonn_ice","message":"Alvin il est vieux !","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 20:03:41][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"leveonn_ice","message":"!camera","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 20:03:42][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!camera","command":{"prefix":"!","name":"camera","args":[]},"isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false,"user":"leveonn_ice"}}
[21-03-03 20:03:05][server][debug] pushActions {"eventName":"onJoin","eventProps":{"user":"leveonn_ice"}}
[21-03-03 20:03:22][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"leveonn_ice","message":"!pause","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 20:03:74][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"leveonn_ice","message":"!pause 360","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 20:03:75][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 360","command":{"prefix":"!","name":"pause","args":["360"]},"minutes":360,"isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false,"user":"leveonn_ice"}}
[21-03-03 20:03:70][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"leveonn_ice","message":"!pause 3","isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false}}
[21-03-03 20:03:70][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 3","command":{"prefix":"!","name":"pause","args":["3"]},"minutes":3,"isBroadcaster":false,"isMod":true,"isVip":false,"isSubscriber":false,"user":"leveonn_ice"}}
[21-03-03 20:03:80][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!jeu","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 20:03:80][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!jeu","command":{"prefix":"!","name":"jeu","args":[]},"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 20:03:22][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!pause 3","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 20:03:23][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!pause 3","command":{"prefix":"!","name":"pause","args":["3"]},"minutes":3,"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 20:03:61][server][debug] pushActions {"eventName":"onMessage","eventProps":{"user":"arubinu42","message":"!camera","isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true}}
[21-03-03 20:03:61][server][debug] pushActions {"eventName":"onCommand","eventProps":{"message":"!camera","command":{"prefix":"!","name":"camera","args":[]},"isBroadcaster":true,"isMod":false,"isVip":false,"isSubscriber":true,"user":"arubinu42"}}
[21-03-03 20:03:34][server][debug] pushActions {"eventName":"onPart","eventProps":{"user":"leveonn_ice"}}
[21-03-03 21:03:54][server][info] Client disconnected 
[21-03-03 21:03:54][server][info] Overlay disconnected 
[21-03-03 21:03:54][server][info] Client disconnected 
```

**Comment by skarab42** [comment]
Fix by #209
