### ISSUE TITLE
UncaughtException Cannot destructure property 'duration' of 'get(...)' as it is undefined.

### ISSUE THREAD

**Issue by arsouillegamepad** [skarab42/marv#246]
# Marv is redirecting you to this page because an error has occurred. Please complete the report below and send it to help developers resolve this issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Windows_NT 10.0.19042 win32
- Marv: v1.7.0

**Browser**

- Version: [e.g. chrome, safari]

**Additional context**

**Stack trace**

```
UncaughtException: TypeError: Cannot destructure property 'duration' of 'get(...)' as it is undefined.
    at create (C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\actions\types\anime.js:10:11)
    at push (C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\actions\push.js:76:12)
    at C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\twitch\pushActions.js:66:9
    at Array.forEach (<anonymous>)
    at C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\twitch\pushActions.js:60:41
    at Array.forEach (<anonymous>)
    at C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\twitch\pushActions.js:53:13
    at Array.forEach (<anonymous>)
    at pushActions (C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\twitch\pushActions.js:52:31)
    at ChatClient.onPart (C:\Users\Seb\AppData\Local\Programs\marv\resources\app.asar\server\libs\twitch\chat\events\onPart.js:4:3)
```

**Comment by skarab42** [comment]
Hello, tu te rappel ce que tu as fais pour avoir cette erreur ? Merci :)

**Comment by arsouillegamepad** [comment]
Absolument pas car étant sur console a se moment la h ai pas vu le message de suite par contre j ai eu un raid que j ai personnalisé avant et y a pas eu l alerte perso du streamerEnvoyé de mon Galaxy S7 Orange
-------- Message d'origine --------De : skarab42 ***@***.***> Date : 25/07/2021  06:34  (GMT+01:00) À : skarab42/marv ***@***.***> Cc : arsouillegamepad ***@***.***>, Author ***@***.***> Objet : Re: [skarab42/marv] UncaughtException Cannot destructure property 'duration' of 'get(...)' as it is undefined. (#246) 
Hello, tu te rappel ce que tu as fais pour avoir cette erreur ? Merci :)
